#!/usr/bin/env ruby

require_relative 'lib/chess_ui'
require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.on '-s', '--scroll',
    'Allow scrolling back the terminal to see previous board states' do
    options[:scroll] = true
  end

  opts.on '-l', '--labels', 'Display rank and file labels on the chessboard' do
    options[:labels] = true
  end

  opts.on '-g', '--game FILE', 'Load a game from FILE' do |filename|
    begin
      options[:pgn] = File.read(filename)
    rescue IOError
      puts "Error reading from file: '#{filename}'. Please make sure it exists."
    else
      puts "Loading game..."
    end
  end

  opts.on '-r', '--replay N',
  'Replay the loaded game with a N second delay between moves' \
  do |n|
    options[:replay] = n.to_f
  end

  opts.on '-h', '--help', 'Display help' do
    puts opts

    help_file = File.open("help.txt")
    puts help_file.read
    help_file.close()

    exit
  end
end.parse!

ChessUI.new(**options).play_game
